services:
  frontend:
    image: fraolbmax/guzolink-frontend:latest
    container_name: guzolink-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "127.0.0.1:3000:80"



volumes:
  uploads_data: