services:
  backend:
    build: ./backend
    container_name: bookyapp-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./book_store
    container_name: bookyapp-frontend
    ports:
      - "3001:80"

  mongodb:
    image: mongo:latest
    container_name: bookyapp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
