/** Style: Market Ledger — shop discovery is a generous directory with practical location and category context. */
import { Search } from "lucide-react";
import { useMemo } from "react";
import { useSearchParams } from "react-router-dom";
import MarketplaceShell from "../components/layout/MarketplaceShell";
import ShopCard from "../components/common/ShopCard";
import { EmptyState, ErrorState, LoadingBlock } from "../components/common/AsyncState";
import { useShops } from "../features/catalogue/catalogueQueries";
export default function ShopsPage() { const [params, setParams] = useSearchParams(); const filters = useMemo(() => ({ search: params.get("search") || "" }), [params]); const query = useShops(filters); function setSearch(search) { const next = new URLSearchParams(params); search ? next.set("search", search) : next.delete("search"); setParams(next); } return <MarketplaceShell><div className="page-enter mx-auto max-w-[1440px] px-4 py-10 md:px-8"><div className="grid gap-6 border-b border-line pb-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="ledger-label">Merchant directory</p><h1 className="mt-3 max-w-[10ch] font-display text-5xl leading-[.94] tracking-[-.055em]">Meet the shops.</h1></div><div><p className="max-w-xl text-sm leading-7 text-[#646963]">Independent merchants with useful goods, clear identities, and an open door to their catalogue.</p><label className="mt-5 flex items-center gap-2 border border-line bg-[#fffdf7] px-3"><Search size={17} className="text-[#737870]" /><span className="sr-only">Search shops</span><input className="w-full bg-transparent py-3 text-sm outline-none" value={filters.search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by shop or category" /></label></div></div>{query.isLoading ? <div className="mt-8"><LoadingBlock rows={3} /></div> : query.isError ? <div className="mt-8"><ErrorState error={query.error} onRetry={query.refetch} /></div> : query.data.items.length ? <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{query.data.items.map((shop) => <ShopCard key={shop.id} shop={shop} />)}</div> : <div className="mt-8"><EmptyState title="No shops found" description="Try another shop name or browse the full directory." actionLabel="View all shops" actionTo="/shops" /></div>}</div></MarketplaceShell>; }
